import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Fugaz_One } from "next/font/google";
import { Lato } from "next/font/google";

const fugazOne = Fugaz_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-fugaz-one",
});

const lato = Lato({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lato",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={lato.variable} data-theme="light">
			<body className="font-lato" >
				<Navbar />

				{children}

				<Toaster position="top-right" reverseOrder={false} />

				<Footer />
			</body>
		</html>
	);
}
