import { Pitch, InvestmentTier } from "@/lib/types/pitch";

export const mockPitches: Pitch[] = [
	{
		id: 1,
		title: "Solar Smart Panel",
		elevator_pitch: "Energy efficient solar panels for urban homes.",
		detailed_pitch:
			"Our panels reduce electricity costs by up to 30% and integrate with smart home systems.",
		target_amount: 50000,
		raised_amount: 12000,
		profit_share_percent: 15,
		status: "Active",
		investment_start_date: new Date("2025-09-01"),
		investment_end_date: new Date("2025-12-31"),
		created_at: new Date("2025-08-01"),
		updated_at: new Date("2025-08-15"),
		investment_tiers: [
			{
				tier_id: 1,
				pitch_id: 1,
				name: "Seed",
				min_amount: 500,
				max_amount: 1999,
				multiplier: 1.2,
				created_at: new Date("2025-09-01"),
			},
			{
				tier_id: 2,
				pitch_id: 1,
				name: "Series A",
				min_amount: 2000,
				max_amount: 4999,
				multiplier: 1.5,
				created_at: new Date("2025-09-01"),
			},
		],
	},
	{
		id: 2,
		title: "Eco-Friendly Sneakers",
		elevator_pitch: "Sustainable sneakers made from recycled materials.",
		detailed_pitch:
			"Durable, stylish, and environmentally conscious footwear for the modern consumer.",
		target_amount: 80000,
		raised_amount: 50000,
		profit_share_percent: 10,
		status: "Funded",
		investment_start_date: new Date("2025-08-15"),
		investment_end_date: new Date("2025-11-30"),
		created_at: new Date("2025-07-10"),
		updated_at: new Date("2025-08-20"),
		investment_tiers: [
			{
				tier_id: 3,
				pitch_id: 2,
				name: "Bronze",
				min_amount: 1000,
				max_amount: 4999,
				multiplier: 1.1,
				created_at: new Date("2025-08-15"),
			},
			{
				tier_id: 4,
				pitch_id: 2,
				name: "Gold",
				min_amount: 5000,
				max_amount: 19999,
				multiplier: 1.5,
				created_at: new Date("2025-08-15"),
			},
		],
	},
	{
		id: 3,
		title: "Smart Garden System",
		elevator_pitch: "Automated gardening system for small apartments.",
		detailed_pitch:
			"Controls watering, light, and nutrition for indoor plants using AI sensors.",
		target_amount: 30000,
		raised_amount: 15000,
		profit_share_percent: 20,
		status: "Draft",
		investment_start_date: new Date("2025-09-10"),
		investment_end_date: new Date("2025-12-15"),
		created_at: new Date("2025-08-05"),
		updated_at: new Date("2025-08-10"),
		investment_tiers: [],
	},
];
